################################################################################
# Gitlab CI integration for Esante.
################################################################################

include:
  - local: .gitlab/ci/jobs/*.yml # Include abstract jobs to be extended
  - local: .gitlab/ci/fragments/*.yml # Include any non-job yml fragments

default:
  tags:
    - ans-g2-g3

################################################################################
# Stages.
################################################################################
# Order is important for dependencies!
stages:
  - build
  - lint
  - audits
  - packaging
  - deploy

################################################################################
# Build job.
################################################################################
site-build:
  extends: [ .site:build, .node12-image ]

################################################################################
# Code linter & Test jobs.
################################################################################
site-lint:
  extends: [ .site:lint, .node12-image]

################################################################################
# Packaging
################################################################################
package_generate:
  extends: [ .package:generate ]

package_upload:
  extends: [ .package:upload ]

################################################################################
# Deploy
################################################################################
synchro_github:
  extends: [ .synchro:github ]