#!/usr/bin/env bash

## Compile styleguide and site based on src
##
## Usage: fin compile

# Abort if anything fails
set -e

source "${PROJECT_ROOT}/.docksal/commands/helpers"

#-------------------------- Execution --------------------------------

# Site updating
echo -e "${green_bg} Step 1 ${NC}${green} Compiling...${NC}"

time -p compile

echo -e "${green_bg} DONE! ${NC}${green} Completed all compiling steps.${NC}"

#-------------------------- END: Execution --------------------------------
