#!/usr/bin/env sh

#: exec_target = node

## Execute gulp commands
##
## Usage: fin gulp

# Abort if anything fails
set -e

source "${PROJECT_ROOT}/.docksal/commands/helpers"

cd "${DOCROOT_PATH}"

if [ ! -d "node_modules" ]
then
  echo_yellow "Node modules don't exist."
  echo_green "Installing node modules..."

  npm ci
fi

#-------------------------- Execution --------------------------------

./node_modules/.bin/gulp ${@}
