#!/usr/bin/env bash

## Define helpers for others scripts.
##
## No "fin" usage.

#-------------------------- Settings --------------------------------

PROJECT_ROOT="/var/www"
DOCROOT_PATH="${PROJECT_ROOT}/web"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
lavender_bg='\033[1;30;0;44m'
yellow='\033[1;33m'
NC='\033[0m'

echo_red () { echo -e "${red}$1${NC}"; }
echo_green () { echo -e "${green}$1${NC}"; }
echo_green_bg () { echo -e "${green_bg}$1${NC}"; }
echo_lavender_bg () { echo -e "${lavender_bg}$1${NC}"; }
echo_yellow () { echo -e "${yellow}$1${NC}"; }


# Compile SCSS
compile ()
{
  echo_green "Compiling"
  fin gulp
}

#-------------------------- END: Helper functions --------------------------------
