#!/usr/bin/env bash

## Update site
##
## Usage: fin update

# Abort if anything fails
set -e

source "${PROJECT_ROOT}/.docksal/commands/helpers"

#-------------------------- Execution --------------------------------

# Site updating
echo -e "${green_bg} Step 2 ${NC}${green} Updating site...${NC}"

time -p compile

echo -e "${green_bg} DONE! ${NC}${green} Completed all updating steps.${NC}"

#-------------------------- END: Execution --------------------------------
