name: NodeJS with Gulp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.4.0

    - name: Build
      run: npm install
      
    - name: Build gulp
      run: gulp
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      #with: // Ok Version 6.1.0 
        # GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)
        #token: 
        # optional, default is ${{ github.token }}
        # Relative path under $GITHUB_WORKSPACE to the repository. Defaults to $GITHUB_WORKSPACE.
