name: NodeJS with Gulp

on:
  push:
    branches: [main]

permissions:
  pull-requests: write
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 12

    - name: Build
      run: npm install
      
    - name: Build gulp
      run: gulp

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        branch: github-pages
        
