################################################################################
# Base template.
################################################################################

################################################################################
# Runner.
################################################################################

.rui_runner:
  # Use internal Runner
  tags:
    - rui

.rue_runner:
  # Use external Runner
  tags:
    - rue

################################################################################
# SSH Access.
################################################################################

.ssh:
  # Before deploy ssh private key need to be create in gitlab CI/CD variables
  # And ssh public key need to be add on ~/.ssh/authorized_keys files in VM wanted.
  before_script:
    - echo "Create ssh agent."
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_DEPLOY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    #- bash ${CI_PROJECT_DIR}/.gitlab/ci/teams_webhook/teams_notifications.sh "$WEBHOOK_URL" "start" "$CI_JOB_NAME" "$GITLAB_USER_NAME" "$CI_JOB_STARTED_AT" "$CI_JOB_URL" "$CI_JOB_MANUAL"
  after_script:
    #- bash ${CI_PROJECT_DIR}/.gitlab/ci/teams_webhook/teams_notifications.sh "$WEBHOOK_URL" "$CI_JOB_STATUS" "$CI_JOB_NAME" "$GITLAB_USER_NAME" "$CI_JOB_STARTED_AT" "$CI_JOB_URL" "$CI_JOB_MANUAL"

.css-lint:
  stage: tests
  needs: []
  script:
    - |
      cd ${CI_PROJECT_DIR}/web/themes/custom/${FOLDER}
      npm ci
      npm run lint:css
